# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\User: sha512

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        api_key_user_provider:
            id: api_key_user_provider
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        apidoc:
            pattern: ^/apidoc
            anonymous: ~
            security: false

        api_register:
            pattern: ^/api/1.0/user/register
            anonymous: ~
            security: false

        secured_area:
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator
            provider: api_key_user_provider

