services:
    api_key_user_provider:
        class: AppBundle\Security\ApiKeyUserProvider
        arguments:
          - @app.service.user_service

    apikey_authenticator:
        class:  AppBundle\Security\ApiKeyAuthenticator
        public: false

    app.service.user_service:
        class: AppBundle\Service\UserService
        arguments:
          - @doctrine.orm.default_entity_manager
          - @fos_user.user_manager
          - @validator

    app.service.work_time_service:
        class: AppBundle\Service\WorkTimeService
        arguments:
          - @doctrine.orm.default_entity_manager
          - @validator

    app.service.project_service:
        class: AppBundle\Service\ProjectService
        arguments:
          - @doctrine.orm.default_entity_manager
          - @validator